version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - '2501:80'
    volumes:
      - .:/code
      - ./config/docker/nginx/nginx.conf:/etc/nginx/nginx.conf

  php:
    build: config/docker/php
    volumes:
      - .:/code

  pgsql:
    image: postgres:latest
    ports:
      - '2502:5432'
    environment:
      POSTGRES_USER: johnnoel-uk
      POSTGRES_PASSWORD: johnnoel-uk
