version: 2.1
jobs:
    build:
        working_directory: /tmp
        docker:
            - image: cimg/base
        steps:
            - attach_workspace:
                  at: /tmp
            - run: tar cjf johnnoel-uk.tar.bz2 -C /tmp/johnnoel-uk/ .
            - store_artifacts:
                  path: /tmp/johnnoel-uk.tar.bz2

    deploy:
        working_directory: /tmp/johnnoel-uk
        docker:
            - image: johnnoel/php:7.4
        steps:
            - attach_workspace:
                  at: /tmp
            - add_ssh_keys:
                  fingerprints:
                      - "0a:3e:5d:cc:d1:21:30:32:19:f9:33:3b:77:a1:b0:18"
            - run: doctl auth init --access-token "${DIGITALOCEAN_API_KEY}"
            - run: echo "export EXTERNAL_IP=$(wget -qO- http://checkip.amazonaws.com/)" >> $BASH_ENV
            - run: doctl compute firewall add-rules --inbound-rules "protocol:tcp,ports:22,address:${EXTERNAL_IP}/32" "${DIGITALOCEAN_FIREWALL_ID}"
            - run: ssh-keyscan -H 67.207.69.0 >> ~/.ssh/known_hosts
            - run: dep -vvv deploy "https://circleci.com/api/v1.1/project/github/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/latest/artifacts" "${CIRCLE_TOKEN}"
            - run: doctl compute firewall remove-rules --inbound-rules "protocol:tcp,ports:22,address:${EXTERNAL_IP}/32" "${DIGITALOCEAN_FIREWALL_ID}"

workflows:
    version: 2
    install-and-test:
        jobs:
            - build:
                  filters:
                      branches:
                          only: main
            - deploy:
                  requires:
                      - build
                  filters:
                      branches:
                          only: main
