version: 2.1
jobs:
  install:
    working_directory: /tmp/johnnoel-uk
    docker:
      - image: circleci/php:7.4-cli-node
    steps:
      - checkout
      - run: sudo composer self-update
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            - composer-v1-
      - restore_cache:
          keys:
            - npm-v1-{{ checksum "package-lock.json" }}
            - npm-v1-
      - run: composer install --no-interaction --no-progress
      - run: npm install
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - save_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: /tmp/
          paths:
            - johnnoel-uk

  coding-standards:
    working_directory: /tmp/johnnoel-uk
    docker:
      - image: circleci/php:7.4-cli
    steps:
      - attach_workspace:
          at: /tmp
      - run: vendor/bin/phpcs -n src

  static-analysis:
    working_directory: /tmp/johnnoel-uk
    docker:
      - image: circleci/php:7.4-cli
    steps:
      - attach_workspace:
          at: /tmp
      - run: php -d memory_limit=512M vendor/bin/phpstan analyse

  test:
    working_directory: /tmp/johnnoel-uk
    docker:
      - image: johnnoel/php:7.4-cli
        environment:
          APP_ENV: test
          DATABASE_URL: postgresql://johnnoel-uk:johnnoel-uk@localhost/johnnoel_uk_test?serverVersion=13&charset=utf8
      - image: circleci/postgres:13-ram
        environment:
          POSTGRES_USER: johnnoel-uk
          POSTGRES_PASSWORD: johnnoel-uk
          POSTGRES_DB: johnnoel_uk_test
    steps:
      - attach_workspace:
          at: /tmp
      - run: bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration
      - run: bin/console doctrine:fixtures:load --no-interaction
      - run: bin/phpunit --stop-on-failure --log-junit junitreport.xml
      - store_test_results:
          path: /tmp/johnnoel-uk/junitreport.xml

  build:
    working_directory: /tmp
    docker:
      - image: circleci/php:7.4-cli-node
        environment:
          NODE_ENV: production
          APP_ENV: prod
    steps:
      - attach_workspace:
          at: /tmp
      - run: npm run prod --prefix /tmp/johnnoel-uk
      - run: npm run imagemin --prefix /tmp/johnnoel-uk
      - run: npm run tumblr --prefix /tmp/johnnoel-uk
      - run: composer install --working-dir /tmp/johnnoel-uk --no-interaction --no-dev --no-progress --no-scripts
      - run: composer dump-autoload --working-dir /tmp/johnnoel-uk --no-interaction --no-dev --optimize
      - run: rm -rf /tmp/johnnoel-uk/node_modules /tmp/johnnoel-uk/var/log/* /tmp/johnnoel-uk/var/cache/*
      - run: tar cjf johnnoel-uk.tar.bz2 -C /tmp/johnnoel-uk/ .
      - store_artifacts:
          path: /tmp/johnnoel-uk.tar.bz2

workflows:
  version: 2
  install-and-test:
    jobs:
      - install
      - coding-standards:
          requires:
            - install
      - static-analysis:
          requires:
            - install
      - test:
          requires:
            - install
      - build:
          requires:
            - coding-standards
            - static-analysis
            - test
          filters:
            branches:
              only: main
