parameters:
    secret: '%env(APP_SECRET)%'

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\MessageHandler\ContactNotificationHandler:
        arguments:
            $contactAddress: '%env(CONTACT_ADDRESS)%'

    App\Validator\HCaptchaValidator:
        arguments:
            $secretKey: '%env(HCAPTCHA_SECRET_KEY)%'
            $siteKey: '%env(HCAPTCHA_SITE_KEY)%'
