parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\MessageHandler\ContactNotificationHandler:
        arguments:
            $contactAddress: '%env(CONTACT_ADDRESS)%'

    App\Validator\HCaptchaValidator:
        arguments:
            $secretKey: '%env(HCAPTCHA_SECRET_KEY)%'
            $siteKey: '%env(HCAPTCHA_SITE_KEY)%'

    App\MessageHandler\TakeProjectScreenshotHandler:
        arguments:
            $screenshotPath: '%kernel.project_dir%/public/projects'
